### PR TITLE
Proposed changes for release 0.2.7

### LINKED ISSUE #3: Update package meta data
- the package release tarball 0.2.6 contains still the version 0.2.5 in configure.ac
- maintainers e-mail address should be updated
- man page also contains version tag 0.2.5
- Changelog could be updated

Sorry to not create a PR, but I'm limited in time at the moment.

### PR DESCRIPTION
**Pull request by mhei**
Please find in this pull requests some changes which improve this package,
at least in my opinion :smile:

At least it fixes #3, so that we could trigger distributions to pick up the new
release.

Feel free to select and reject according to your linking.

### CODE REVIEW

**Comment by rdoeffinger** [comment]
Wow, you sure made some effort there! It seems you know a good bit more about autotools than me, so I'll just take it as it is.
The one thing I'd still like to have (but I'll be travelling the next 2 weeks) is a --version or similar option for the binary, plus a release script that updates the version, sets a tag and builds the Windows executable.
But I guess that will have to wait.

**Comment by rdoeffinger** [comment]
There actually is a version in the binary. I wrote a quick release script and made a new release.
Made a few fixes as well (some dates in NEWS were wrong).

**Comment by mhei** [comment]
Opps, I see - thank you for fixing these things - seems it was too late yesterday :smiley:

**Comment by mhei** [comment]
Just another note: this package is based on autoconf/automake. The usual way to distribute the sources is to run "make dist" and then you get a "iec16022-0.2.7.tar.xz" file in the package root directory. It would be nice if you could add this to the release as download.
The difference to just downloading the tag sources link from Github is, that ./configure & Co are already present in the tarball. Distributions usually have "built-in support" for the usual procedure of "./configure && make all && make test && make install" to create the deb/ipk/rpm.

**Comment by rdoeffinger** [comment]
I opened a ticket for that, though I don't really much like even more steps to the release.
I'd kind of rather throw out the whole autotools stuff, for a project of this size the complexity and obfuscation it (and especially libtool) adds seems very hard to justify.
But it would almost certainly break something...

**Comment by rdoeffinger** [comment]
I decided to implement a "make dist" step, and I uploaded the corresponding files, if you want to check them.
It seems mostly fine, but I suspect CREDITS should maybe be added to EXTRA_DIST...

**Comment by mhei** [comment]
Looks good to me, that you very much for the extra efforts. Yes, for CREDITS it makes sense to add to EXTRA_DIST to get the file included in the tarball. Then there are TODO and release.sh left, but I don't know whether its worth to include these both too...

**Pull request merged**
